### ISSUE TITLE
Missing zoneinfo.zip  when including a timezone parameter into a job config

### ISSUE THREAD

**Issue by bomu-bomu** [victorcoder/docker-dkron#6]
I've set up dkron via docker-compose and applied the official image 

But when I tried the example from the getting start page, the error occurred.
first job config
```
$ curl localhost:8080/v1/jobs -XPOST -d '{
  "name": "job1",
  "schedule": "@every 10s",
  "timezone": "Europe/Berlin",
  "owner": "Platform Team",
  "owner_email": "platform@example.com",
  "disabled": false,
  "tags": {
    "dkron_server": "true:1"
  },                     
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "date"
  }
}'
$
```
Error from dkron logs
```
dkron_1   | time="2019-02-22T04:05:08Z" level=info msg="Error #01: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory" node=4164f29ffdb9
```

I removed timezone config and retried and it worked
```
$ curl localhost:8080/v1/jobs -XPOST -d '{
  "name": "job1",
  "schedule": "@every 10s",
  "owner": "Platform Team",
  "owner_email": "platform@example.com",
  "disabled": false,
  "tags": {
    "dkron_server": "true:1"
  },                        
  "concurrency": "allow",
  "executor": "shell",
  "executor_config": {
    "command": "date"
  }                  
}'
{"name":"job1","timezone":"","schedule":"@every 10s","owner":"Platform Team","owner_email":"platform@example.com","success_count":0,"error_count":0,"last_success":"0001-01-01T00:00:00Z","last_error":"0001-01-01T00:00:00Z","disabled":false,"tags":{"dkron_server":"true:1"},"retries":0,"dependent_jobs":null,"parent_job":"","processors":null,"concurrency":"allow","executor":"shell","executor_config":{"command":"date"},"status":""}
$
```
Could you include zoneinfo into this official image??

Ref:docker-conpose.xml
```
---
version: '2'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8300"
    hostname: node1
    command: agent -server -bootstrap -client=0.0.0.0
  dkron:
    image: dkron/dkron
    depends_on:
      - consul
    ports:
      - "8080:8080"
      - "8946:8946"
    volumes:
     - ./:/gopath/src/github.com/victorcoder/dkron
    environment:
      - GODEBUG=netdns=go
    command: agent --server --backend=consul --backend-machine=consul:8500 --join=dkron:8946 --log-level=debug
```
